--BUSINESS UNIT LEVEL

SELECT 
ROLLEDUP.BUSINESS_UNIT AS BUSINESS_UNIT_ROLLED,
ROLLEDUP.START_DATE AS START_DATE_ROLLED,
ROLLEDUP.SUM_SALES AS SUM_SALES_ROLLED,
ACTUAL.BUSINESS_UNIT AS BUSINESS_UNIT_ACTUAL,
ACTUAL.START_DATE AS START_DATE_ACTUAL,
ACTUAL.SUM_SALES AS SUM_SALES_ACTUAL
FROM
(select business_unit,start_date,sum(sales) SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NULL
group by business_unit,start_date) ROLLEDUP
FULL OUTER JOIN 
(select business_unit,start_date,sales SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE STORE_ID IS NULL AND REGION IS NULL AND `GROUP` IS NULL AND VPN IS NULL) ACTUAL
ON ROLLEDUP.business_unit = ACTUAL.business_unit
AND ROLLEDUP.start_date = ACTUAL.start_date
WHERE ABS(ROLLEDUP.SUM_SALES - ACTUAL.SUM_SALES) > 0.001

Result: Query returned zero records.

--BUSINESS UNIT AND GROUP LEVEL

SELECT 
ROLLEDUP.BUSINESS_UNIT AS BUSINESS_UNIT_ROLLED,
ROLLEDUP.GROUP_NAME AS GROUP_NAME_ROLLED,
ROLLEDUP.START_DATE AS START_DATE_ROLLED,
ROLLEDUP.SUM_SALES AS SUM_SALES_ROLLED,
ACTUAL.BUSINESS_UNIT AS BUSINESS_UNIT_ACTUAL,
ACTUAL.GROUP_NAME AS GROUP_NAME_ACTUAL,
ACTUAL.START_DATE AS START_DATE_ACTUAL,
ACTUAL.SUM_SALES AS SUM_SALES_ACTUAL
FROM
(select business_unit,`GROUP` GROUP_NAME,start_date,sum(sales) SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NOT NULL
group by business_unit,`GROUP`,start_date) ROLLEDUP
FULL OUTER JOIN 
(select business_unit,`GROUP` GROUP_NAME,start_date,sales SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NULL AND REGION IS NULL AND `GROUP` IS NOT NULL AND VPN IS NULL) ACTUAL
ON ROLLEDUP.business_unit = ACTUAL.business_unit
AND ROLLEDUP.GROUP_NAME = ACTUAL.GROUP_NAME
AND ROLLEDUP.start_date = ACTUAL.start_date
WHERE ABS(ROLLEDUP.SUM_SALES - ACTUAL.SUM_SALES) > 0.001


Result: Query returned zero records.

--BUSINESS UNIT , GROUP LEVEL AND REGION LEVEL

SELECT 
ROLLEDUP.BUSINESS_UNIT AS BUSINESS_UNIT_ROLLED,
ROLLEDUP.GROUP_NAME AS GROUP_NAME_ROLLED,
ROLLEDUP.REGION AS REGION_ROLLED,
ROLLEDUP.START_DATE AS START_DATE_ROLLED,
ROLLEDUP.SUM_SALES AS SUM_SALES_ROLLED,
ACTUAL.BUSINESS_UNIT AS BUSINESS_UNIT_ACTUAL,
ACTUAL.GROUP_NAME AS GROUP_NAME_ACTUAL,
ACTUAL.REGION AS ACTUAL_ROLLED,
ACTUAL.START_DATE AS START_DATE_ACTUAL,
ACTUAL.SUM_SALES AS SUM_SALES_ACTUAL
FROM
(select business_unit,`GROUP` GROUP_NAME,REGION,start_date,sum(sales) SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NOT NULL
group by business_unit,`GROUP`,REGION,start_date) ROLLEDUP
FULL OUTER JOIN 
(select business_unit,`GROUP` GROUP_NAME,REGION,start_date,sales SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NULL) ACTUAL
ON ROLLEDUP.business_unit = ACTUAL.business_unit
AND ROLLEDUP.REGION = ACTUAL.REGION
AND ROLLEDUP.GROUP_NAME = ACTUAL.GROUP_NAME
AND ROLLEDUP.start_date = ACTUAL.start_date
WHERE ABS(ROLLEDUP.SUM_SALES - ACTUAL.SUM_SALES) > 0.001

--BUSINESS UNIT , GROUP LEVEL, REGION LEVEL AND STORE LEVEL

SELECT 
ROLLEDUP.BUSINESS_UNIT AS BUSINESS_UNIT_ROLLED,
ROLLEDUP.GROUP_NAME AS GROUP_NAME_ROLLED,
ROLLEDUP.REGION AS REGION_ROLLED,
ROLLEDUP.STORE AS STORE_ROLLED,
ROLLEDUP.START_DATE AS START_DATE_ROLLED,
ROLLEDUP.SUM_SALES AS SUM_SALES_ROLLED,
ACTUAL.BUSINESS_UNIT AS BUSINESS_UNIT_ACTUAL,
ACTUAL.GROUP_NAME AS GROUP_NAME_ACTUAL,
ACTUAL.REGION AS REGION_ACTUAL,
ACTUAL.STORE AS STORE_ACTUAL,
ACTUAL.START_DATE AS START_DATE_ACTUAL,
ACTUAL.SUM_SALES AS SUM_SALES_ACTUAL
FROM
(select business_unit,`GROUP` GROUP_NAME,REGION,STORE,start_date,sum(sales) SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NOT NULL
group by business_unit,`GROUP`,REGION,STORE,start_date) ROLLEDUP
FULL OUTER JOIN 
(select business_unit,`GROUP` GROUP_NAME,REGION,STORE,start_date,sales SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NULL) ACTUAL
ON ROLLEDUP.business_unit = ACTUAL.business_unit
AND ROLLEDUP.GROUP_NAME = ACTUAL.GROUP_NAME
AND ROLLEDUP.REGION = ACTUAL.REGION
AND ROLLEDUP.STORE = ACTUAL.STORE
AND ROLLEDUP.start_date = ACTUAL.start_date
WHERE ABS(ROLLEDUP.SUM_SALES - ACTUAL.SUM_SALES) > 0.001

--BUSINESS UNIT , GROUP LEVEL, REGION LEVEL, STORE LEVEL AND VPN LEVEL

SELECT 
ROLLEDUP.BUSINESS_UNIT AS BUSINESS_UNIT_ROLLED,
ROLLEDUP.GROUP_NAME AS GROUP_NAME_ROLLED,
ROLLEDUP.REGION AS REGION_ROLLED,
ROLLEDUP.STORE AS STORE_ROLLED,
ROLLEDUP.VPN AS VPN_ROLLED,
ROLLEDUP.START_DATE AS START_DATE_ROLLED,
ROLLEDUP.SUM_SALES AS SUM_SALES_ROLLED,
ACTUAL.BUSINESS_UNIT AS BUSINESS_UNIT_ACTUAL,
ACTUAL.GROUP_NAME AS GROUP_NAME_ACTUAL,
ACTUAL.REGION AS REGION_ACTUAL,
ACTUAL.STORE AS STORE_ACTUAL,
ACTUAL.VPN AS VPN_ACTUAL,
ACTUAL.START_DATE AS START_DATE_ACTUAL,
ACTUAL.SUM_SALES AS SUM_SALES_ACTUAL
FROM
(select business_unit,`GROUP` GROUP_NAME,REGION,STORE,VPN,start_date,sum(sales) SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NOT NULL
group by business_unit,`GROUP`,REGION,STORE,VPN,start_date) ROLLEDUP
FULL OUTER JOIN 
(select business_unit,`GROUP` GROUP_NAME,REGION,STORE,VPN,start_date,sales SUM_SALES FROM `kopari.nordstrom_sales` 
WHERE BUSINESS_UNIT IS NOT NULL AND STORE_ID IS NOT NULL AND REGION IS NOT NULL AND `GROUP` IS NOT NULL AND VPN IS NULL) ACTUAL
ON ROLLEDUP.business_unit = ACTUAL.business_unit
AND ROLLEDUP.GROUP_NAME = ACTUAL.GROUP_NAME
AND ROLLEDUP.REGION = ACTUAL.REGION
AND ROLLEDUP.STORE = ACTUAL.STORE
AND ROLLEDUP.VPN = ACTUAL.VPN
AND ROLLEDUP.start_date = ACTUAL.start_date
WHERE ABS(ROLLEDUP.SUM_SALES - ACTUAL.SUM_SALES) > 0.001